### PR TITLE
Fix date parsing

### PR DESCRIPTION
**Pull request by mkdynamic**
Re: #9

### CODE REVIEW

**Comment by mkdynamic** [comment]
@kindjar Can you CR this please?

**Comment by kindjar** [comment]
The code changes look good, but the tests using `01` for the date fail in python 3... just use `1` with no leading zero. The Travis builds for 2.6 and 2.7 are also failing, but for other reasons.

The 2.7 failure looks like it might be a timezone configuration issue. Perhaps the Travis container does not have any time zone info installed? In which case maybe adding `pytz` to the `pip install flake8 mock --use-mirrors` line in `.travis.yml` would fix it? (I'm totally guessing, based on the fact that the python docs for the `datetime` module say that the standard library doesn't include any tzinfo.)

The 2.6 failure is happening because the recently-release flake8 3.0.0 dropped python 2.6 support (http://flake8.pycqa.org/en/latest/release-notes/3.0.0.html). It looks like we only run flake8 under python 2.6, maybe because it theoretically produces the same output for every version? If that's the case, we can just switch to only running it for python 3.4? Or we can pin the flake8 version to something that works for 2.6.

**Comment by mkdynamic** [comment]
> The code changes look good, but the tests using 01 for the date fail in python 3... just use 1 with no leading zero. 

Odd, suite appeared to pass locally. What am I doing wrong?

```
$ tox
GLOB sdist-make: ~/setup.py
python2.6 inst-nodeps: ~/.tox/dist/delighted-1.1.0.zip
python2.6 installed: delighted==1.1.0,flake8==2.5.5,funcsigs==1.0.2,mccabe==0.4.0,mock==2.0.0,pbr==1.10.0,pep8==1.7.0,pyflakes==1.0.0,requests==2.10.0,six==1.10.0
python2.6 runtests: PYTHONHASHSEED='3403353540'
python2.6 runtests: commands[0] | flake8 delighted
python2.6 runtests: commands[1] | python -W always setup.py test
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running test
running egg_info
writing requirements to delighted.egg-info/requires.txt
writing top-level names to delighted.egg-info/top_level.txt
writing dependency_links to delighted.egg-info/dependency_links.txt
writing delighted.egg-info/PKG-INFO
reading manifest file 'delighted.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'delighted.egg-info/SOURCES.txt'
running build_ext
test_instantiating_client_requires_api_key (test.test_client.ClientTest) ... ok
test_creating_a_survey_response (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person_other_client (test.test_resource.TestResource) ... ok
test_deleting_pending_survey_requests_for_a_person (test.test_resource.TestResource) ... ok
test_listing_all_bounces (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses_expand_person (test.test_resource.TestResource) ... ok
test_listing_all_unsubscribes (test.test_resource.TestResource) ... ok
test_retrieving_a_survey_response_expand_person (test.test_resource.TestResource) ... ok
test_retrieving_metrics (test.test_resource.TestResource) ... ok
test_retrieving_metrics_other_client (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_date_object (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_unixtimestamp (test.test_resource.TestResource) ... ok
test_unsubscribing_a_person (test.test_resource.TestResource) ... ok
test_updating_a_survey_response (test.test_resource.TestResource) ... ok

----------------------------------------------------------------------
Ran 16 tests in 0.013s

OK
python2.7 inst-nodeps: ~/.tox/dist/delighted-1.1.0.zip
python2.7 installed: delighted==1.1.0,flake8==2.5.5,funcsigs==1.0.2,mccabe==0.4.0,mock==2.0.0,pbr==1.10.0,pep8==1.7.0,pyflakes==1.0.0,requests==2.10.0,six==1.10.0
python2.7 runtests: PYTHONHASHSEED='3403353540'
python2.7 runtests: commands[0] | flake8 delighted
python2.7 runtests: commands[1] | python -W always setup.py test
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running test
running egg_info
writing requirements to delighted.egg-info/requires.txt
writing top-level names to delighted.egg-info/top_level.txt
writing dependency_links to delighted.egg-info/dependency_links.txt
writing delighted.egg-info/PKG-INFO
reading manifest file 'delighted.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'delighted.egg-info/SOURCES.txt'
running build_ext
test_instantiating_client_requires_api_key (test.test_client.ClientTest) ... ok
test_creating_a_survey_response (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person_other_client (test.test_resource.TestResource) ... ok
test_deleting_pending_survey_requests_for_a_person (test.test_resource.TestResource) ... ok
test_listing_all_bounces (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses_expand_person (test.test_resource.TestResource) ... ok
test_listing_all_unsubscribes (test.test_resource.TestResource) ... ok
test_retrieving_a_survey_response_expand_person (test.test_resource.TestResource) ... ok
test_retrieving_metrics (test.test_resource.TestResource) ... ok
test_retrieving_metrics_other_client (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_date_object (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_unixtimestamp (test.test_resource.TestResource) ... ok
test_unsubscribing_a_person (test.test_resource.TestResource) ... ok
test_updating_a_survey_response (test.test_resource.TestResource) ... ok

----------------------------------------------------------------------
Ran 16 tests in 0.012s

OK
python3.2 inst-nodeps: ~/.tox/dist/delighted-1.1.0.zip
python3.2 installed: delighted==1.1.0,flake8==2.5.5,funcsigs==1.0.2,mccabe==0.4.0,mock==2.0.0,pbr==1.10.0,pep8==1.7.0,pyflakes==1.0.0,requests==2.10.0,six==1.10.0
python3.2 runtests: PYTHONHASHSEED='3403353540'
python3.2 runtests: commands[0] | flake8 delighted
python3.2 runtests: commands[1] | python -W always setup.py test
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running test
running egg_info
writing requirements to delighted.egg-info/requires.txt
writing top-level names to delighted.egg-info/top_level.txt
writing dependency_links to delighted.egg-info/dependency_links.txt
writing delighted.egg-info/PKG-INFO
reading manifest file 'delighted.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'delighted.egg-info/SOURCES.txt'
running build_ext
test_instantiating_client_requires_api_key (test.test_client.ClientTest) ... ok
test_creating_a_survey_response (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person_other_client (test.test_resource.TestResource) ... ok
test_deleting_pending_survey_requests_for_a_person (test.test_resource.TestResource) ... ok
test_listing_all_bounces (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses_expand_person (test.test_resource.TestResource) ... ok
test_listing_all_unsubscribes (test.test_resource.TestResource) ... ok
test_retrieving_a_survey_response_expand_person (test.test_resource.TestResource) ... ok
test_retrieving_metrics (test.test_resource.TestResource) ... ok
test_retrieving_metrics_other_client (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_date_object (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_unixtimestamp (test.test_resource.TestResource) ... ok
test_unsubscribing_a_person (test.test_resource.TestResource) ... ok
test_updating_a_survey_response (test.test_resource.TestResource) ... ok

----------------------------------------------------------------------
Ran 16 tests in 0.012s

OK
python3.3 inst-nodeps: ~/.tox/dist/delighted-1.1.0.zip
python3.3 installed: delighted==1.1.0,flake8==2.5.5,funcsigs==1.0.2,mccabe==0.4.0,mock==2.0.0,pbr==1.10.0,pep8==1.7.0,pyflakes==1.0.0,requests==2.10.0,six==1.10.0
python3.3 runtests: PYTHONHASHSEED='3403353540'
python3.3 runtests: commands[0] | flake8 delighted
python3.3 runtests: commands[1] | python -W always setup.py test
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running test
running egg_info
writing requirements to delighted.egg-info/requires.txt
writing top-level names to delighted.egg-info/top_level.txt
writing dependency_links to delighted.egg-info/dependency_links.txt
writing delighted.egg-info/PKG-INFO
reading manifest file 'delighted.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'delighted.egg-info/SOURCES.txt'
running build_ext
test_instantiating_client_requires_api_key (test.test_client.ClientTest) ... ok
test_creating_a_survey_response (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person_other_client (test.test_resource.TestResource) ... ok
test_deleting_pending_survey_requests_for_a_person (test.test_resource.TestResource) ... ok
test_listing_all_bounces (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses_expand_person (test.test_resource.TestResource) ... ok
test_listing_all_unsubscribes (test.test_resource.TestResource) ... ok
test_retrieving_a_survey_response_expand_person (test.test_resource.TestResource) ... ok
test_retrieving_metrics (test.test_resource.TestResource) ... ok
test_retrieving_metrics_other_client (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_date_object (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_unixtimestamp (test.test_resource.TestResource) ... ok
test_unsubscribing_a_person (test.test_resource.TestResource) ... ok
test_updating_a_survey_response (test.test_resource.TestResource) ... ok

----------------------------------------------------------------------
Ran 16 tests in 0.009s

OK
python3.4 inst-nodeps: ~/.tox/dist/delighted-1.1.0.zip
python3.4 installed: delighted==1.1.0,flake8==2.5.5,funcsigs==1.0.2,mccabe==0.4.0,mock==2.0.0,pbr==1.10.0,pep8==1.7.0,pyflakes==1.0.0,requests==2.10.0,six==1.10.0
python3.4 runtests: PYTHONHASHSEED='3403353540'
python3.4 runtests: commands[0] | flake8 delighted
python3.4 runtests: commands[1] | python -W always setup.py test
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running test
running egg_info
writing requirements to delighted.egg-info/requires.txt
writing top-level names to delighted.egg-info/top_level.txt
writing dependency_links to delighted.egg-info/dependency_links.txt
writing delighted.egg-info/PKG-INFO
reading manifest file 'delighted.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'delighted.egg-info/SOURCES.txt'
running build_ext
test_instantiating_client_requires_api_key (test.test_client.ClientTest) ... ok
test_creating_a_survey_response (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person_other_client (test.test_resource.TestResource) ... ok
test_deleting_pending_survey_requests_for_a_person (test.test_resource.TestResource) ... ok
test_listing_all_bounces (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses_expand_person (test.test_resource.TestResource) ... ok
test_listing_all_unsubscribes (test.test_resource.TestResource) ... ok
test_retrieving_a_survey_response_expand_person (test.test_resource.TestResource) ... ok
test_retrieving_metrics (test.test_resource.TestResource) ... ok
test_retrieving_metrics_other_client (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_date_object (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_unixtimestamp (test.test_resource.TestResource) ... ok
test_unsubscribing_a_person (test.test_resource.TestResource) ... ok
test_updating_a_survey_response (test.test_resource.TestResource) ... ok

----------------------------------------------------------------------
Ran 16 tests in 0.011s

OK
pypy inst-nodeps: ~/.tox/dist/delighted-1.1.0.zip
pypy installed: cffi==1.7.0,configparser==3.5.0,delighted==1.1.0,enum34==1.1.6,flake8==3.0.2,funcsigs==1.0.2,greenlet==0.4.9,mccabe==0.5.0,mock==2.0.0,pbr==1.10.0,pycodestyle==2.0.0,pyflakes==1.2.3,readline==6.2.4.1,requests==2.10.0,six==1.10.0
pypy runtests: PYTHONHASHSEED='3403353540'
pypy runtests: commands[0] | flake8 delighted
pypy runtests: commands[1] | python -W always setup.py test
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running test
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
running egg_info
writing delighted.egg-info/PKG-INFO
writing dependency_links to delighted.egg-info/dependency_links.txt
writing requirements to delighted.egg-info/requires.txt
writing top-level names to delighted.egg-info/top_level.txt
reading manifest file 'delighted.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'delighted.egg-info/SOURCES.txt'
running build_ext
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/pypy/5.3.0/libexec/lib-python/2.7/pkgutil.py:186: ImportWarning: Not importing directory '~/.tox/pypy/site-packages/backports' missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
test_instantiating_client_requires_api_key (test.test_client.ClientTest) ... ok
test_creating_a_survey_response (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person_other_client (test.test_resource.TestResource) ... ok
test_deleting_pending_survey_requests_for_a_person (test.test_resource.TestResource) ... ok
test_listing_all_bounces (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses_expand_person (test.test_resource.TestResource) ... ok
test_listing_all_unsubscribes (test.test_resource.TestResource) ... ok
test_retrieving_a_survey_response_expand_person (test.test_resource.TestResource) ... ok
test_retrieving_metrics (test.test_resource.TestResource) ... ok
test_retrieving_metrics_other_client (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_date_object (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_unixtimestamp (test.test_resource.TestResource) ... ok
test_unsubscribing_a_person (test.test_resource.TestResource) ... ok
test_updating_a_survey_response (test.test_resource.TestResource) ... ok

----------------------------------------------------------------------
Ran 16 tests in 0.040s

OK
pypy3.2 inst-nodeps: ~/.tox/dist/delighted-1.1.0.zip
pypy3.2 installed: delighted==1.1.0,flake8==2.5.5,funcsigs==1.0.2,mccabe==0.4.0,mock==2.0.0,pbr==1.10.0,pep8==1.7.0,pyflakes==1.0.0,requests==2.10.0,six==1.10.0
pypy3.2 runtests: PYTHONHASHSEED='3403353540'
pypy3.2 runtests: commands[0] | flake8 delighted
pypy3.2 runtests: commands[1] | python -W always setup.py test
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running test
running egg_info
writing requirements to delighted.egg-info/requires.txt
writing top-level names to delighted.egg-info/top_level.txt
writing dependency_links to delighted.egg-info/dependency_links.txt
writing delighted.egg-info/PKG-INFO
reading manifest file 'delighted.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'delighted.egg-info/SOURCES.txt'
running build_ext
test_instantiating_client_requires_api_key (test.test_client.ClientTest) ... ok
test_creating_a_survey_response (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person (test.test_resource.TestResource) ... ok
test_creating_or_updating_a_person_other_client (test.test_resource.TestResource) ... ok
test_deleting_pending_survey_requests_for_a_person (test.test_resource.TestResource) ... ok
test_listing_all_bounces (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses (test.test_resource.TestResource) ... ok
test_listing_all_survey_responses_expand_person (test.test_resource.TestResource) ... ok
test_listing_all_unsubscribes (test.test_resource.TestResource) ... ok
test_retrieving_a_survey_response_expand_person (test.test_resource.TestResource) ... ok
test_retrieving_metrics (test.test_resource.TestResource) ... ok
test_retrieving_metrics_other_client (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_date_object (test.test_resource.TestResource) ... ok
test_retrieving_metrics_range_unixtimestamp (test.test_resource.TestResource) ... ok
test_unsubscribing_a_person (test.test_resource.TestResource) ... ok
test_updating_a_survey_response (test.test_resource.TestResource) ... ok

----------------------------------------------------------------------
Ran 16 tests in 0.011s

OK
___________________________________________________________ summary ___________________________________________________________
  python2.6: commands succeeded
  python2.7: commands succeeded
  python3.2: commands succeeded
  python3.3: commands succeeded
  python3.4: commands succeeded
  pypy: commands succeeded
  pypy3.2: commands succeeded
  congratulations :)
```

> The 2.7 failure looks like it might be a timezone configuration issue. Perhaps the Travis container does not have any time zone info installed? In which case maybe adding pytz to the pip install flake8 mock --use-mirrors line in .travis.yml would fix it? (I'm totally guessing, based on the fact that the python docs for the datetime module say that the standard library doesn't include any tzinfo.)

My knowledge of Python date libs is basically non existent, but I suspect the way we convert datetime objects to UNIX timestamps is dependent on the environment time zone (possibly expecting PDT, which is why the suite passed on my machine?).

I may need to enlist your assistance to fix this :)

**Comment by kindjar** [comment]
Your 2.6 suite probably passes because you have an older version of flake8 already installed or cached. When I explicitly installed flake8 3.0.2, the flake8 command gave the same error we see in TravisCI. 

Your 2.7 suite probably passes because your python install did come with timezone data—or I'm totally wrong about why the tests fail on TravisCI (maybe it's applying a default timezone or a different DST rule).

I have _no_ idea why your 3.3 and 3.4 tests pass... I can open up a python3.4 session and immediately get problems trying to use a leading `0`:

``` python
benjamin ~$ python3.4
Python 3.4.3 (default, Jul 13 2015, 12:18:23) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 == 1
True
>>> 1 == 01
  File "<stdin>", line 1
    1 == 01
          ^
SyntaxError: invalid token
>>> 
```

The change to drop the old octal format (leading zero) is discussed briefly here: https://docs.python.org/3.0/whatsnew/3.0.html#new-syntax

It's been a few years since I fought with Python's date/time libraries, but I'll see if I can figure out the 2.7 issue. :)

**Comment by kindjar** [comment]
Converting a python `date` object to an epoch timestamp is inherently problematic, because `date` objects don't support timezone information, so although dates do get converted to localtime, it appears that they do not get the correct daylight saving or summer time offset applied (they seem to use whatever the current UTC offset is, regardless of whether the same offset would apply on the date being converted).

We should be using `datetime` objects with explicit timezones in our example code and in our tests rather than glossing over this detail.

However, to cover the case where a customer passes in just a date, I have figured out how to convert that date to a local datetime, then get that local datetime's epoch timestamp. I'm still going to update the example code, though, because it's much better for clients to be explicit about what timezone should be used when converting to epoch timestamps.

**Comment by mkdynamic** [comment]
> Converting a python date object to an epoch timestamp is inherently problematic, because date objects don't support timezone information, so although dates do get converted to localtime, it appears that they do not get the correct daylight saving or summer time offset applied (they seem to use whatever the current UTC offset is, regardless of whether the same offset would apply on the date being converted).

Gotcha.

> We should be using datetime objects with explicit timezones in our example code and in our tests rather than glossing over this detail.

Yea, +1.

> However, to cover the case where a customer passes in just a date, I have figured out how to convert that date to a local datetime, then get that local datetime's epoch timestamp. I'm still going to update the example code, though, because it's much better for clients to be explicit about what timezone should be used when converting to epoch timestamps.

Great, I think that is good.

**Comment by mkdynamic** [comment]
(Please feel free to push to this branch btw. if you want/need.)

**Comment by kindjar** [comment]
@mkdynamic Can you take a look at CR these changes? I tweaked how we handle dates and how we deal with a lack of timezone. I removed some code I didn't understand that was protecting against timetuples with a length of 6; I'm not sure how they could ever be that size—if you have any insight about that, let me know. I also added some tests to cover timezones both present and absent.

**Pull request merged**
